source "http://rubygems.org"
gem "redcarpet"
gem "RedCloth"
gem "rdoc", "~>3.6"
gem "org-ruby", ">= 0.9.0"
gem "creole", "~>0.3.6"
gem "wikicloth", "=0.6.0"
gem "literati", "= 0.0.3"
gem "asciidoctor", "= 0.1.4"
gem "rake"
