source "http://rubygems.org"
gemspec
gem "redcarpet"
gem "RedCloth"
gem "rdoc", "~>3.6"
gem "org-ruby", "= 0.9.1"
gem "creole", "~>0.3.6"
gem "wikicloth", "=0.6.0"
gem "asciidoctor", "= 0.1.4"
gem "rake"
