# Example API
This is an example Web API described in the [API Blueprint format](https://github.com/apiaryio/api-blueprint).

## Message Resource [/message]
An example resource.

### Retrieve Message [GET]
Retrieve the message.

+ Response 200 (text/plain)

        Hello World!
