#!/usr/bin/env bash
set -e

# process it, and print everything from the first <h1> to </body>
mandoc -Thtml -Ofragment "$@" \
| xml -q tr --html --omit-decl  "$(dirname "$0")/man2html.xslt" - \
| awk '
	/<h1/      { flag = 1 }
	/<\/body>/ { flag = 0 }
	flag
'
