#!/usr/bin/env python
"""
    zerodoc translator script for github-markup

    Copyright (C) 2014 Pablo Martin <pablo at odkq.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import sys
import zerodoc.html
import zerodoc.parse

d, r = zerodoc.parse.parse(sys.stdin.read())
if d == None:
    sys.exit(1)
sys.stdout.write(zerodoc.html.write(d, ['ditaa', 'datauri', 'noheaders',
                                        'pygments']))
# pygments is actually nopygments ...
sys.stdout.flush()
sys.exit(0)
